# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Moments by Mason"
subtitle: "Your Game, Your Moment"
author: "Mason Durant"

header:
  title: "Moments by Mason"
  subtitle: "Your Game, Your Moment"

footer:
  name: "Mason Durant"
  bio: "I started taking photos because I love capturing moments that tell a story. Sports quickly became my favorite subject because every play and every reaction happens so fast. What began as a hobby soon turned into a passion for freezing those split-second memories so they can be relived again and again. I created this website to share my work and to give others a chance to see the game and the people in it through my lens."
  github: ""

web_design: "AJ"

social_urls:
  instagram: "https://www.instagram.com/moments_by_mason_"
  twitter:
  facebook:
  dribbble:
  linkedin:
  github:

# Configure which exif data to display
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
